In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Online Retail.csv', encoding = 'latin1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [3]:
df.shape

(541909, 8)

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
df.duplicated().sum()

5268

In [6]:
df['CustomerID'].nunique()

4372

In [7]:
df = df.dropna(subset = ['CustomerID'])

In [8]:
df.shape

(406829, 8)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(401604, 8)

In [11]:
df['Total_Revenue'] = df['UnitPrice'] * df['Quantity']

In [12]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total_Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceNo      401604 non-null  object
 1   StockCode      401604 non-null  object
 2   Description    401604 non-null  object
 3   Quantity       401604 non-null  int64
 4   InvoiceDate    401604 non-null  object
 5   UnitPrice      401604 non-null  float64
 6   CustomerID     401604 non-null  float64
 7   Country        401604 non-null  object
 8   Total_Revenue  401604 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 30.6+ MB

In [14]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [15]:
df['InvoiceDate'] = df['InvoiceDate'].dt.date

In [16]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate']).dt.normalize()

In [17]:
df['Month'] = df['InvoiceDate'].dt.month

In [18]:
df['Year'] = df['InvoiceDate'].dt.year

In [19]:
df['MonthName'] = df['InvoiceDate'].dt.month_name()

In [20]:
df['InvoiceNo'].astype(str).str.startswith('C').sum()

8872

In [21]:
df[df['InvoiceNo'].astype(str).str.startswith('C')].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total_Revenue,Month,Year,MonthName
141,C536379,D,Discount,-1,2010-12-01,27.50,14527.0,United Kingdom,-27.50,12,2010,December
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01,4.65,15311.0,United Kingdom,-4.65,12,2010,December
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01,1.65,17548.0,United Kingdom,-19.80,12,2010,December
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01,0.29,17548.0,United Kingdom,-6.96,12,2010,December
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01,0.29,17548.0,United Kingdom,-6.96,12,2010,December